const h=document.querySelector('[data-split]');h.innerHTML=[...h.textContent].map((c,i)=>c===' '?' ':('<span class="char" style="animation-delay:'+(.08+i*.025)+'s">'+c+'</span>')).join('');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in');else if(e.boundingClientRect.top>0)e.target.classList.remove('in')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
let tick=false;addEventListener('scroll',()=>{if(!tick){requestAnimationFrame(()=>{let e=document.querySelector('.parallax'),r=e.getBoundingClientRect();e.style.transform='translate3d(0,'+((innerHeight/2-r.top-r.height/2)*.08)+'px,0)';tick=false});tick=true}},{passive:true});
const data=[['Full-stack development','Build frontend and backend seamlessly. Exact understands your entire stack and helps you ship faster.','import { supabase } from "@/lib/supabase"\n\nexport default async function handler(req,res) {\n // AI suggestion: Add pagination\n const { data } = await supabase\n  .from("products").select("*")\n return res.status(200).json(data)\n}'],['Debug and refactor','Trace bugs across files and apply safe project-wide fixes without broken imports.','Error at auth.ts:42\n\nϟ Exact analysis\nSession accessed before initialization.\n\nSuggested fix:\nconst session = await getSession()'],['API integration','Connect services with generated types, validation, and error handling.','const stripe = new Stripe(API_KEY)\n\nexport async function checkout(items) {\n return stripe.sessions.create({items})\n}'],['Testing and CI/CD','Generate meaningful tests, diagnose failed builds, and keep delivery green.','describe("auth", () => {\n it("rejects weak passwords", async () => {\n  expect(await signUp("123")).toFail()\n })\n})\n\n✓ 28 tests passed']];function use(i){useTitle.textContent=data[i][0];useText.textContent=data[i][1];useCode.textContent=data[i][2]}use(0);document.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const i=+b.dataset.use,frame=document.querySelector('.use-code-frame'),canvas=document.querySelector('.use-canvas');if(b.classList.contains('active'))return;document.querySelectorAll('[data-use]').forEach(x=>x.classList.remove('active'));b.classList.add('active');frame.classList.add('switching');setTimeout(()=>{canvas.dataset.scene=i;use(i);frame.classList.remove('switching')},260)});
document.querySelectorAll('[data-bill]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-bill]').forEach(x=>x.classList.remove('active'));b.classList.add('active');price.childNodes[0].nodeValue=b.dataset.bill==='y'?'€23':'€29'});
document.querySelector('.copy').onclick=function(){this.querySelector('b').textContent='Copied!';navigator.clipboard?.writeText('npm install -g exact');setTimeout(()=>this.querySelector('b').textContent='Copy',1200)};
document.querySelectorAll('details').forEach(d=>d.ontoggle=()=>{if(d.open)document.querySelectorAll('details').forEach(x=>{if(x!==d)x.open=false})});

const featureVisuals=[...document.querySelectorAll('.feature-visual')];const featureMotion=()=>{featureVisuals.forEach((el,i)=>{const r=el.parentElement.getBoundingClientRect(),progress=Math.max(0,Math.min(1,(innerHeight*.9-r.top)/(innerHeight*.62))),direction=i%2===0?-1:1,x=direction*(1-progress)*62,y=(1-progress)*30;el.style.transform='translate3d('+x+'px,'+y+'px,0) scale('+(0.985+progress*.015)+')';el.classList.toggle('motion-in',progress>.06&&r.bottom>0)})};addEventListener('scroll',featureMotion,{passive:true});addEventListener('resize',featureMotion);featureMotion();

const quoteColumns=[...document.querySelectorAll('.quote-column')];const quoteMotion=()=>{quoteColumns.forEach((col,i)=>{const wall=col.parentElement,r=wall.getBoundingClientRect(),p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height))),offset=[28,-18,16][i]*(p-.5);col.style.transform='translate3d(0,'+offset+'px,0)'})};addEventListener('scroll',quoteMotion,{passive:true});quoteMotion();

const finalEditor=document.querySelector('.final-editor');const finalEditorMotion=()=>{if(!finalEditor)return;const r=finalEditor.parentElement.getBoundingClientRect(),p=Math.max(-1,Math.min(1,(innerHeight/2-r.top-r.height/2)/innerHeight));finalEditor.style.translate='0 '+(p*22)+'px'};addEventListener('scroll',finalEditorMotion,{passive:true});finalEditorMotion();
