const A='./public/assets/';
const projects=[['Arrows','Branding / Web Design / Motion','V1tByJz04fgbUrzLuxw9VcL5c.jpeg'],['Chantalle','Branding / Product Design','0VKk1N7SRkJEWFlbyFBYB9HcU.jpg'],['Papyrus','Branding / Product Design','PWcGNEdcfiRatuMonJopF932DaM.jpeg'],['London Museum','Branding / Motion / Product Design','m8nLqdpsVhbQtOULeyBY3OleY3U.jpeg'],['Bullseye','Branding / Web Design / Development','0TObKlZh1ClmcgEP0dGtoojnyXc.jpeg'],['Interference','Product Design','MaHZeDtDy86YDU3iUd5QNSx6tCI.jpeg']];
const services=[['Website Design','Every website we design is crafted to engage and inspire, built on proven principles of what makes users stay, explore, and return.'],['Product Design','We transform complex user needs into intuitive, elegant solutions that solve real business challenges and create meaningful interactions between people and technology.'],['Branding','Our branding process goes beyond visual identity, crafting narratives that capture your unique essence and create lasting emotional connections.'],['Motion Graphics','We bring ideas to life through dynamic animations that communicate complex concepts with clarity, creativity, and visual storytelling.'],['Development','We combine technical excellence with strategic thinking, building robust digital solutions that are scalable, performant, and aligned with your goals.']];
const processSteps=[['Strategy & Research','We start by understanding your business, your goals, and your market. This sets the foundation for work that actually performs.'],['Design & Prototype','From rough sketches to working prototypes, we design solutions that solve real problems while looking great.'],['Build, Test & Optimize','We carefully build your solution, test with real users, and refine based on data and feedback to ensure everything works flawlessly.'],['Launch & Support','After a smooth launch, we monitor performance and provide support to ensure your product continues to deliver value over time.']];
const app=document.querySelector('#app');
app.innerHTML=`
<header class="nav"><a class="mark" href="#top">OPUS</a><button class="menu">Menu</button><nav><a href="#work">Projects</a><a href="#journal">Blog</a><a href="#about">About</a><a href="#contact">Contact</a></nav></header>
<main id="top">
 <section class="hero shell"><div class="hero-title"><h1><span>STUDIO</span><span>OPUS</span></h1></div><div class="hero-media media-reveal"><img data-depth=".15" src="${A}FPeepKKHxtAQvBoZw06THrhotfE.png" alt="Opus studio object"></div><div class="hero-copy"><h2 class="split">At Opus, we help companies build stronger brands, better products, and websites that actually perform.</h2><a class="arrow-link" href="#services">Browse our services <i>↘</i></a></div></section>
<section class="vision shell"><p class="eyebrow">Our Vision</p><div><h2 class="display split">Whether it's a website, an app, or a complete brand identity — we create work that works.</h2><p>Good design isn't just about looks. It's about solving real problems and getting results. Here’s ours.</p><div class="metrics"><article><strong data-count="46">0</strong><b>+</b><small>Projects delivered</small></article><article><strong data-count="92">0</strong><b>%</b><small>Client retention</small></article><article><b>$</b><strong data-count="20">0</strong><b>M</b><small>Client revenue impacted</small></article></div></div></section>
 <div class="ticker"><div>${Array(4).fill('<span>Strategy</span><span>Design</span><span>Development</span><span>Motion</span>').join('')}</div></div>
 <section id="services" class="services"><div class="services-sticky"><h2 class="display split">This is how we help ambitious companies succeed.</h2><div class="service-track">${services.map((s,i)=>`<article class="${i===0?'active':''}" tabindex="0"><small>0${i+1}</small><h3>${s[0]}</h3><p>${s[1]}</p><i>+</i></article>`).join('')}</div></div></section>
 <section class="process shell"><p class="eyebrow">Our Process</p><h2 class="display split">Our mission is to help businesses grow through strategic design, creating work that performs as good as it looks.</h2><div class="process-list">${processSteps.map((x,i)=>`<article class="${i===0?'active':''}" tabindex="0"><small>0${i+1}</small><h3>${x[0]}</h3><p>${x[1]}</p><button aria-label="Select ${x[0]}"><i></i></button></article>`).join('')}</div></section>
<section id="work" class="work shell"><div class="section-head"><p class="eyebrow">Our work</p><div><h2 class="display">Our recent projects</h2><p>Dive into our diverse collection of innovative projects, where creativity meets cutting-edge technology.</p></div><a class="arrow-link" href="#work">All projects <i>↘</i></a></div><div class="project-grid">${projects.map(p=>`<a class="project media-reveal" href="#"><div><img data-depth=".1" src="${A+p[2]}" alt="${p[0]}"></div><header><h3>${p[0]}</h3><p>${p[1].split(' / ').map(tag=>`<span>${tag}</span>`).join('')}</p></header></a>`).join('')}</div></section>
 <section class="black-cta"><div><h2 class="display split">Want to build something better?</h2><p>Our team brings together design, development, and strategic thinking to help you grow.</p><a href="#contact">Start now <i>↘</i></a></div></section>
 <section id="about" class="culture shell"><h2>or get to know us first!</h2><div class="culture-numbers"><div><strong>19</strong><span>talented<br>individuals</span></div><div><strong>134+</strong><span>projects<br>later</span></div><p>combined experience</p></div><div class="team-copy"><div><h2 class="display split">We are a group of positive thinkers, dedicated to making a difference in the digital world.</h2><p>We combine creative vision with technical expertise to help businesses thrive in the digital space.</p><a class="arrow-link" href="#about">Meet the team <i>↘</i></a></div><div class="team-image media-reveal"><img data-depth=".14" src="${A}ECzuL4YY67K9O1ChG9ioW32OpA.jpg" alt="Two women laughing at work"></div></div></section>
 <section class="pricing"><div class="shell"><div class="section-head"><p class="eyebrow">Pricing</p><div><h2 class="display">Start growing today</h2><p>Choose a plan that fits your needs. Get access to our team of designers and developers.</p></div></div><div class="toggle"><span>Monthly</span><button aria-label="Toggle yearly"><i></i></button><span>Yearly</span><b>Save 20%</b></div><div class="plans">${[['Essential','2900'],['Growth','4900'],['Scale','7900']].map((x,i)=>`<article class="${i===1?'featured':''}"><p>${x[0]}</p><h3>$${x[1]}<small>/month</small></h3><p>For businesses ready to level up their digital presence with an expert creative team.</p><a href="#contact">Get Started Today ↗</a><ul><li>Slack Communication</li><li>${i+2} Team members</li><li>Web design & development</li><li>Monthly design iterations</li><li>Fast response time</li></ul></article>`).join('')}</div></div></section>
 <section class="testimonials shell"><p class="eyebrow">Testimonials</p><h2 class="display">Real results, real feedback</h2><div class="quote-wrap"><blockquote>“Finally found a team that understands both design and business. Our brand now perfectly captures what makes us different.”</blockquote><p>Tom Bennett<br><span>Founder @ Terrain Coffee</span></p><div><button class="prev">←</button><button class="next">→</button></div></div></section>
 <section class="faq shell"><div><p class="eyebrow">FAQ</p><h2 class="display">Common Qs</h2><p>Get quick answers about working with us and our approach to digital solutions.</p></div><div>${['What types of projects do you typically work on?','How long does a typical project take?',"What's your development process like?",'Do you provide ongoing support after launch?','Can you work with our existing systems and team?'].map((q,i)=>`<article><button><span>${q}</span><i>+</i></button><p>${i?'Every engagement is scoped around your business and built through a transparent, collaborative process.':'We specialize in websites, digital products, brand identities and motion systems for ambitious companies.'}</p></article>`).join('')}</div></section>
 <section id="journal" class="journal shell"><div class="section-head"><p class="eyebrow">Blog</p><div><h2 class="display">Our perspectives</h2><p>Stay ahead with actionable insights and practical strategies for digital success.</p></div></div>${['Custom vs. Off-the-Shelf: Choose Wisely','Design That Converts: Our Approach','7 Critical Steps to Successfully Launch Your Digital Product'].map((x,i)=>`<a href="#"><span>Jan ${16-i*7}, 2025</span><h3>${x}</h3><i>↗</i></a>`).join('')}</section>
</main><footer id="contact"><div class="footer-top"><video autoplay muted loop playsinline aria-hidden="true"><source src="${A}footer-night.mp4" type="video/mp4"></video><div class="footer-shade"></div><div class="footer-cta"><h2>Let's build something<br>great together</h2><p>Get in touch to explore how we can help your<br>business reach its full potential.</p><a href="mailto:contact@opushq.com">Get Started Today</a></div></div><div class="footer-main shell"><div class="footer-brand"><h2>OPUS</h2><p>We help businesses succeed in the digital space by creating thoughtful solutions that combine smart design, reliable technology, and a deep understanding of what your users really need.</p></div><div class="footer-email"><p>You can also email us at:</p><a href="mailto:contact@opushq.com">contact@opushq.com</a></div><div class="footer-social"><a href="#">Facebook</a><a href="#">Instagram</a><a href="#">Dribble</a><a href="#">Behance</a></div><nav><a href="#top">Home</a><a href="#work">Projects</a><a href="#journal">Blog</a><a href="#about">About Us</a><a href="#contact">Contact</a></nav></div><div class="legal shell"><span>@2026 Opus, All Rights Reserved</span><span>Privacy Policy &nbsp; Terms of Service</span></div></footer>`;

document.querySelector('.menu').onclick=()=>document.body.classList.toggle('menu-open');
document.querySelectorAll('.split').forEach(el=>{el.innerHTML=el.textContent.trim().split(/\s+/).map((w,i)=>`<span style="--i:${i}">${w}</span>`).join(' ')});
document.querySelectorAll('.vision,.process,.work,.culture,.pricing,.testimonials,.faq,.journal,.footer-top').forEach((section,index)=>{section.classList.add('motion-section');section.style.setProperty('--section-index',index)});
document.querySelectorAll('.metrics article,.plans article,.journal>a,.faq article,.section-head>*').forEach((item,index)=>{item.classList.add('motion-item');item.style.setProperty('--item-delay',`${(index%4)*70}ms`)});
const io=new IntersectionObserver(entries=>entries.forEach(entry=>{entry.target.classList.toggle('in',entry.isIntersecting);entry.target.classList.toggle('out-top',!entry.isIntersecting&&entry.boundingClientRect.top<0)}),{rootMargin:'-7% 0px -9% 0px',threshold:[0,.08,.18,.45]});document.querySelectorAll('.split,.media-reveal,.process-list article,.project,.motion-section,.motion-item').forEach(x=>io.observe(x));
const metricIO=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return; e.target.querySelectorAll('[data-count]').forEach(n=>{let s=0,t=+n.dataset.count;const id=setInterval(()=>{s=Math.min(t,s+Math.ceil(t/36));n.textContent=s;if(s===t)clearInterval(id)},32)});metricIO.unobserve(e.target)}),{threshold:.4});metricIO.observe(document.querySelector('.metrics'));
const quotes=[['Finally found a team that understands both design and business. Our brand now perfectly captures what makes us different.','Tom Bennett','Founder @ Terrain Coffee'],["The level of strategic thinking they brought was unexpected. They didn't just build what we asked for — they made it better.",'Sarah Chen','COO @ Stellar Analytics'],['Every feature they built was focused on driving results. They transformed how we think about digital.','Marcus Rodriguez','Director @ Greenwave Solar']];let qi=0;function quote(d){qi=(qi+d+quotes.length)%quotes.length;const w=document.querySelector('.quote-wrap');w.classList.add('changing');setTimeout(()=>{w.querySelector('blockquote').textContent='“'+quotes[qi][0]+'”';w.querySelector('p').innerHTML=quotes[qi][1]+'<br><span>'+quotes[qi][2]+'</span>';w.classList.remove('changing')},260)}document.querySelector('.next').onclick=()=>quote(1);document.querySelector('.prev').onclick=()=>quote(-1);
document.querySelectorAll('.faq article button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));document.querySelector('.toggle button').onclick=e=>e.currentTarget.classList.toggle('on');
function activateWithin(selector,item){document.querySelectorAll(`${selector} article`).forEach(card=>card.classList.toggle('active',card===item))}
document.querySelectorAll('.service-track article').forEach(card=>{card.addEventListener('mouseenter',()=>activateWithin('.service-track',card));card.addEventListener('focus',()=>activateWithin('.service-track',card));card.addEventListener('click',()=>activateWithin('.service-track',card))});
document.querySelectorAll('.process-list article').forEach(card=>{card.addEventListener('mouseenter',()=>activateWithin('.process-list',card));card.addEventListener('focus',()=>activateWithin('.process-list',card));card.addEventListener('click',()=>activateWithin('.process-list',card))});
let ticking=false;function motion(){const y=scrollY,view=innerHeight;document.documentElement.style.setProperty('--scroll',y);document.body.classList.toggle('scrolled',y>40);document.querySelectorAll('[data-depth]').forEach(img=>{const r=img.parentElement.getBoundingClientRect(),p=Math.max(-1,Math.min(1,(view/2-r.top-r.height/2)/view));img.style.transform=`translate3d(0,${p*Number(img.dataset.depth)*180}px,0) scale(${1.12-Math.abs(p)*.025})`});const srv=document.querySelector('.services'),r=srv.getBoundingClientRect(),progress=Math.max(0,Math.min(1,-r.top/(r.height-view)));srv.style.setProperty('--x',`${progress*-62}%`);const hero=document.querySelector('.hero'),hr=hero.getBoundingClientRect(),hp=Math.max(0,Math.min(1,-hr.top/view));hero.style.setProperty('--hero-exit',hp);document.querySelectorAll('.black-cta,.footer-top').forEach(el=>{const er=el.getBoundingClientRect(),ep=Math.max(-1,Math.min(1,(view/2-er.top-er.height/2)/view));el.style.setProperty('--local-progress',ep)});ticking=false}addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(motion)}},{passive:true});addEventListener('resize',motion);motion();
